[package]
name = "media-core"
edition.workspace = true
rust-version.workspace = true
version.workspace = true
publish.workspace = true

[dependencies]
async-trait.workspace = true
thiserror.workspace = true
time.workspace = true
uuid = { version = "=1.23.4", default-features = false, features = ["std", "v4"] }

[lints]
workspace = true
